FROM node:latest AS builder

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/
#COPY .env ./
COPY uploads ./uploads
# Install app dependencies
RUN npm install
RUN npx prisma generate
#RUN npx prisma db push
COPY . .

RUN npm run build

FROM node:latest


ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}


COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
#COPY --from=builder /app/.env ./
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/uploads ./uploads
EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]
